course_name = "创新训练课A"
course_code = ""

notices = ""

lecturers = []

textbooks = []

online_resources = []

course = []

exam = []

advice = []

schedule = []

[[related_links]]
content = "mobile-robot - 使用 STM32 和 OpenMV 制作的物流机器人: https://github.com/kowyo/mobile-robot"
[related_links.author]
name = ""
link = ""
date = ""

[[related_links]]
content = "Bike-Computer - 基于 ESP-32 和 esp-idf v4.4 的 自行车 GPS 码表: https://github.com/MaxwellJay256/Bike-Computer"
[related_links.author]
name = ""
link = ""
date = ""

[[related_links]]
content = "stockanalysis-freshman-year-project - 基于机器学习的股票预测和分析: https://github.com/efJerryYang/stockanalysis-freshman-year-project"
[related_links.author]
name = ""
link = ""
date = ""

[[misc]]
content = """
Awesome HITSZ 大一立项

收集 HITSZ 中有意思的大一立项项目。
如果你发现了有意思的大一立项项目，或者想分享自己的大一立项项目，欢迎创建 Pull Request 来增加新內容。
"""
[misc.author]
name = ""
link = ""
date = ""