SimilarID = []
ID = "AUTO2003A"
Name = "创新训练课A"
[[CourseProperty]]
CourseType = "必修"
CourseID = "AUTO2003A"
CourseName = "创新训练课A"
Credit = 1.0
GPAInfluence = "考查"
CourseHour = "1周"
GradeComposition = []
[[CourseProperty.Major]]
Year = "2020_2021"
Name = [ "2019级:自动化", "2020级:自动化",]
Degree = "本"

[[CourseProperty.GradeSemesters]]
Grade = "大一"
Semester = "夏"

[[CourseProperty.CourseHourComposition]]
Name = "授课"
Hour = 40


[CourseProperty.GroupCourse]
Link = ""
Desc = ""
Name = ""
Ids = [ "", "", "",]
[[CourseProperty]]
CourseType = "必修"
CourseID = "AUTO2003A"
CourseName = "创新训练课A"
Credit = 1.0
GPAInfluence = "考查"
CourseHour = "1周"
GradeComposition = []
CourseHourComposition = []
[[CourseProperty.Major]]
Year = "2022_2023"
Name = [ "2021级:自动化", "2022级:自动化",]
Degree = "本"

[[CourseProperty.GradeSemesters]]
Grade = "大一"
Semester = "夏"


[CourseProperty.GroupCourse]
Link = ""
Desc = ""
Name = ""
Ids = [ "", "", "",]
