course_name = "创新训练课A"
course_code = "AUTO2003A"
repo_type = "normal"
description = """
收集 HITSZ 中有意思的大一立项项目：

- [mobile-robot](https://github.com/kowyo/mobile-robot) - 使用 STM32 和 OpenMV 制作的物流机器人
- [Bike-Computer](https://github.com/MaxwellJay256/Bike-Computer) - 基于 ESP-32 和 esp-idf v4.4 的 自行车 GPS 码表
- [stockanalysis-freshman-year-project](https://github.com/efJerryYang/stockanalysis-freshman-year-project) - 基于机器学习的股票预测和分析

如果你发现了有意思的大一立项项目，或者想分享自己的大一立项项目，欢迎创建 Pull Request 来增加新內容。
"""